from .syw import ShengYiWu
from .elem_type import Ys_Elem_Type

all_syw = {
    ShengYiWu.PART_HUA: [
        ShengYiWu(ShengYiWu.XI_SHI_ZHI_GE, ShengYiWu.PART_HUA,
                  atk=14, crit_damage=0.14, energy_recharge=0.104, crit_rate=0.109),

        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_HUA, crit_rate=0.14,
                  atk=14, crit_damage=0.078, energy_recharge=0.168),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_HUA,
                  crit_rate=0.07, crit_damage=0.194, atk=39, def_per=0.058),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_HUA, energy_recharge=0.058,
                  crit_damage=0.078, elem_mastery=54, crit_rate=0.109),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_HUA, crit_damage=0.21,
                  hp_percent=0.152, crit_rate=0.031, def_v=23),

        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_HUA, crit_rate=0.066,
                  crit_damage=0.287, elem_mastery=16, atk_per=0.099),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_HUA, atk=16,
                  hp_percent=0.181, crit_damage=0.148, atk_per=0.058),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_HUA, energy_recharge=0.123,
                  crit_rate=0.101, hp_percent=0.053, crit_damage=0.117),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_HUA, def_per=0.066,
                  crit_damage=0.148, crit_rate=0.105, energy_recharge=0.104),

        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_HUA,
                  energy_recharge=0.045, hp_percent=0.053, crit_damage=0.326, atk_per=0.099),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_HUA,
                  crit_damage=0.218, crit_rate=0.035, hp_percent=0.157, atk=31),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_HUA,
                  crit_rate=0.097, crit_damage=0.132, elem_mastery=21, atk=29),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_HUA,
                  crit_damage=0.14, def_per=0.051, hp_percent=0.146, crit_rate=0.07),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_HUA, crit_rate=0.14,
                  atk_per=0.117, crit_damage=0.07, energy_recharge=0.045),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_HUA, crit_damage=0.078,
                  crit_rate=0.148, elem_mastery=16, atk_per=0.099),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_HUA, crit_damage=0.218,
                  def_per=0.073, hp_percent=0.105, energy_recharge=0.104),

        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_HUA,
                  crit_rate=0.128, crit_damage=0.225,  def_per=0.066, elem_mastery=16),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_HUA,
                  crit_rate=0.035, crit_damage=0.249, energy_recharge=0.117, atk_per=0.099),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_HUA,
                  atk=35, def_v=42, crit_rate=0.039, crit_damage=0.303),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_HUA,
                  elem_mastery=42, crit_rate=0.105, atk=14, hp_percent=0.134),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_HUA,
                  crit_damage=0.155, hp_percent=0.053, atk=35, crit_rate=0.105),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_HUA,
                  def_per=0.073, hp_percent=0.152, crit_rate=0.027, crit_damage=0.202),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_HUA,
                  def_per=0.139, crit_rate=0.101, energy_recharge=0.058, crit_damage=0.124),

        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_HUA,
                  crit_damage=0.14, elem_mastery=44, crit_rate=0.105, def_v=39),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_HUA,
                  crit_damage=0.124, hp_percent=0.099, atk=14, crit_rate=0.124),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_HUA, crit_damage=0.249,
                  energy_recharge=0.065, def_per=0.066, crit_rate=0.089),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_HUA, def_v=23,
                  crit_damage=0.272, elem_mastery=44, energy_recharge=0.065),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_HUA, crit_damage=0.28,
                  hp_percent=0.099, atk_per=0.053, crit_rate=0.027),

        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_HUA,
                  elem_mastery=44, crit_rate=0.105, crit_damage=0.124, def_v=44),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_HUA,
                  crit_rate=0.078, atk_per=0.087, elem_mastery=37, crit_damage=0.225),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_HUA, energy_recharge=0.11,
                  hp_percent=0.152, crit_rate=0.035, elem_mastery=70),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_HUA, def_v=16,
                  elem_mastery=79, hp_percent=0.093, energy_recharge=0.11),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_HUA,
                  crit_damage=0.288, crit_rate=0.062, def_v=21, hp_percent=0.047),

        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_HUA,
                  crit_rate=0.07, def_v=23, hp_percent=0.14, crit_damage=0.194),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_HUA, hp_percent=0.181,
                  energy_recharge=0.123, def_v=23, crit_rate=0.07),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_HUA, atk_per=0.041,
                  crit_rate=0.062, elem_mastery=54, crit_damage=0.21),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_HUA, crit_rate=0.144,
                  crit_damage=0.078, hp_percent=0.105, elem_mastery=40),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_HUA, elem_mastery=44,
                  crit_damage=0.21, def_per=0.066, energy_recharge=0.194),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_HUA, elem_mastery=21,
                  crit_rate=0.066, energy_recharge=0.181, crit_damage=0.124),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_HUA, atk=33,
                  crit_rate=0.066, atk_per=0.111, crit_damage=0.117),

        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_HUA, crit_damage=0.132,
                  crit_rate=0.152, energy_recharge=0.097, def_per=0.073),
        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_HUA, def_v=16,
                  crit_rate=0.035, crit_damage=0.249, atk=29),

        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_HUA, crit_damage=0.132,
                  crit_rate=0.101, atk=16, energy_recharge=0.175),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_HUA, def_v=39,
                  atk=16, crit_damage=0.241, crit_rate=0.066),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_HUA,
                  energy_recharge=0.155, atk=35, hp_percent=0.128, atk_per=0.047),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_HUA, hp_percent=0.134,
                  energy_recharge=0.162, crit_rate=0.074, crit_damage=0.078),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_HUA,
                  energy_recharge=0.117, atk=14, atk_per=0.117, crit_damage=0.264),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_HUA, def_per=0.131,
                  energy_recharge=0.175, def_v=37, crit_damage=0.062),

        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_HUA, crit_rate=0.066,
                  crit_damage=0.148, hp_percent=0.146, def_per=0.109),
        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_HUA, crit_damage=0.054,
                  energy_recharge=0.065, crit_rate=0.132, def_v=39),

        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_HUA, def_per=0.124,
                  crit_damage=0.062, hp_percent=0.111, energy_recharge=0.214),
        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_HUA, energy_recharge=0.227,
                  atk_per=0.058, elem_mastery=44, hp_percent=0.047),
        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_HUA, crit_damage=0.14,
                  energy_recharge=0.065, atk_per=0.099, crit_rate=0.105),

        ShengYiWu(ShengYiWu.YUE_TUAN, ShengYiWu.PART_HUA, elem_mastery=58,
                  crit_damage=0.148, crit_rate=0.078, def_per=0.051),

        ShengYiWu(ShengYiWu.FENG_TAO, ShengYiWu.PART_HUA, crit_damage=0.078,
                  energy_recharge=0.065, atk_per=0.146, crit_rate=0.144),
        ShengYiWu(ShengYiWu.FENG_TAO, ShengYiWu.PART_HUA,
                  atk_per=0.099, crit_rate=0.066, crit_damage=0.202, atk=18),

        ShengYiWu(ShengYiWu.JUE_DOU_SHI, ShengYiWu.PART_HUA,
                  hp_percent=0.157, crit_damage=0.218, crit_rate=0.078, def_v=16),
        ShengYiWu(ShengYiWu.JUE_DOU_SHI, ShengYiWu.PART_HUA,
                  crit_damage=0.14, crit_rate=0.062, def_v=16, def_per=0.168),

        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA, crit_damage=0.194,
                  hp_percent=0.128, atk_per=0.041, energy_recharge=0.104),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA, atk_per=0.105,
                  elem_mastery=19, crit_rate=0.132, energy_recharge=0.11),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA, crit_rate=0.086,
                  crit_damage=0.202, elem_mastery=40, energy_recharge=0.052),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA, elem_mastery=16,
                  atk_per=0.134, crit_damage=0.132, crit_rate=0.089),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA, def_v=21,
                  atk_per=0.134, atk=27, crit_damage=0.218),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA,
                  crit_rate=0.097, energy_recharge=0.13, atk_per=0.111, crit_damage=0.07),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA,
                  atk_per=0.099, atk=14, crit_damage=0.187, energy_recharge=0.11),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA, atk_per=0.163,
                  crit_rate=0.039, crit_damage=0.155, elem_mastery=40),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA, atk_per=0.099,
                  hp_percent=0.099, crit_damage=0.21, energy_recharge=0.058),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_HUA, elem_mastery=16,
                  crit_rate=0.039, crit_damage=0.264, def_v=46), 
    ],
    ShengYiWu.PART_YU: [
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_YU, hp=209,
                  energy_recharge=0.123, hp_percent=0.21, crit_damage=0.124),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_YU, hp=568,
                  crit_damage=0.21, hp_percent=0.053, def_v=56),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_YU, def_v=37,
                  elem_mastery=40, crit_damage=0.256, crit_rate=0.027),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_YU, hp_percent=0.14,
                  elem_mastery=19, crit_rate=0.097, energy_recharge=0.052),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_YU, elem_mastery=37,
                  energy_recharge=0.11, crit_damage=0.14, crit_rate=0.07),

        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_YU,
                  crit_damage=0.202, crit_rate=0.031, hp_percent=0.14, hp=239),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_YU,
                  hp=239, energy_recharge=0.065, crit_damage=0.132, hp_percent=0.181),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_YU, crit_damage=0.194,
                  energy_recharge=0.065, crit_rate=0.062, elem_mastery=37),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_YU, hp=448,
                  crit_damage=0.14, crit_rate=0.136, elem_mastery=16),

        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_YU,
                  hp=568, crit_rate=0.062, hp_percent=0.093, crit_damage=0.187),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_YU,
                  hp=508, crit_rate=0.113, crit_damage=0.117, def_v=42),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_YU,
                  energy_recharge=0.065, crit_damage=0.295, hp=269, hp_percent=0.093),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_YU,
                  atk_per=0.047, hp=538, crit_damage=0.295, crit_rate=0.031),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_YU, def_v=23,
                  crit_damage=0.28, crit_rate=0.027, energy_recharge=0.123),

        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_YU,
                  crit_rate=0.089, hp=478, hp_percent=0.047, crit_damage=0.187),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_YU,
                  hp=508, def_per=0.131, hp_percent=0.093, crit_damage=0.225),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_YU,
                  hp_percent=0.058, crit_rate=0.062, crit_damage=0.132, energy_recharge=0.162),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_YU, def_v=23,
                  crit_rate=0.117, crit_damage=0.194, elem_mastery=23),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_YU, crit_damage=0.07,
                  atk_per=0.058, energy_recharge=0.104, crit_rate=0.136),

        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_YU, hp=508,
                  atk_per=0.099, crit_rate=0.058, crit_damage=0.194),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_YU, atk_per=0.105,
                  crit_rate=0.035, energy_recharge=0.058, elem_mastery=93),

        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_YU, crit_damage=0.078,
                  atk_per=0.041, crit_rate=0.035, elem_mastery=96),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_YU, energy_recharge=0.149,
                  hp_percent=0.117, crit_rate=0.035, crit_damage=0.132),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_YU, def_v=37,
                  crit_damage=0.07, crit_rate=0.144, def_per=0.066),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_YU,
                  crit_damage=0.272, hp=239, crit_rate=0.07, def_v=21),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_YU, crit_damage=0.132,
                  crit_rate=0.066, hp_percent=0.041, elem_mastery=56),

        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_YU, def_per=0.073,
                  atk_per=0.087, crit_rate=0.027, energy_recharge=0.285),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_YU,
                  crit_damage=0.148, def_per=0.117, def_v=19, crit_rate=0.148),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_YU, crit_rate=0.039,
                  crit_damage=0.35, hp_percent=0.041, def_v=39),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_YU, hp=448,
                  crit_damage=0.078, energy_recharge=0.311, hp_percent=0.053),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_YU, hp=807,
                  atk_per=0.047, energy_recharge=0.11, crit_damage=0.171),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_YU, elem_mastery=16,
                  atk_per=0.058, crit_damage=0.148, crit_rate=0.132),

        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_YU,
                  crit_damage=0.225, def_v=23, elem_mastery=40, crit_rate=0.066),
        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_YU, 
                  atk_per=0.041, energy_recharge=0.117, crit_damage=0.124, crit_rate=0.093),

        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_YU, crit_damage=0.132,
                  energy_recharge=0.175, crit_rate=0.101, hp_percent=0.041),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_YU, atk_per=0.111,
                  energy_recharge=0.117, hp_percent=0.21, def_per=0.073),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_YU, hp_percent=0.082,
                  energy_recharge=0.097, atk_per=0.21, crit_rate=0.035),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_YU, atk_per=0.099,
                  energy_recharge=0.246, crit_damage=0.099, crit_rate=0.035),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_YU, def_v=23,
                  crit_rate=0.031, hp=478, hp_percent=0.216),

        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_YU,
                  crit_rate=0.14, atk_per=0.053, hp=478, crit_damage=0.109),
        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_YU,
                  crit_damage=0.14, def_per=0.16, crit_rate=0.101, hp=239),
        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_YU, def_v=16,
                  crit_damage=0.117, crit_rate=0.124, atk_per=0.041),
        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_YU, hp_percent=0.047,
                  def_per=0.066, energy_recharge=0.065, crit_rate=0.167),

        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_YU,
                  elem_mastery=47, def_v=60, hp=269, energy_recharge=0.149),
        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_YU, hp=209,
                  hp_percent=0.157, energy_recharge=0.104, def_v=35),
        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_YU, hp_percent=0.093,
                  crit_rate=0.07, energy_recharge=0.117, atk_per=0.111),

        ShengYiWu(ShengYiWu.RU_LEI, ShengYiWu.PART_YU, crit_rate=0.066,
                  crit_damage=0.218, elem_mastery=63, energy_recharge=0.065),

        ShengYiWu(ShengYiWu.YUE_TUAN, ShengYiWu.PART_YU, elem_mastery=44,
                  crit_damage=0.124, atk_per=0.087, crit_rate=0.101),

        ShengYiWu(ShengYiWu.FENG_TAO, ShengYiWu.PART_YU, hp=239,
                  crit_damage=0.233, atk_per=0.093, crit_rate=0.062),

        ShengYiWu(ShengYiWu.JUE_DOU_SHI, ShengYiWu.PART_YU, hp_percent=0.111,
                  crit_rate=0.167, energy_recharge=0.045, crit_damage=0.062),
        ShengYiWu(ShengYiWu.JUE_DOU_SHI, ShengYiWu.PART_YU, crit_rate=0.144,
                  crit_damage=0.07, hp_percent=0.111, energy_recharge=0.045),

        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU,
                  crit_rate=0.062, crit_damage=0.132, atk_per=0.093, energy_recharge=0.162),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU,
                  def_per=0.139, crit_damage=0.124, elem_mastery=44, crit_rate=0.093),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU,
                  crit_rate=0.113, def_v=42, energy_recharge=0.091, crit_damage=0.124),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU,
                  def_v=23, crit_damage=0.295, hp=538, crit_rate=0.07),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU, crit_damage=0.194,
                  energy_recharge=0.052, elem_mastery=19, hp_percent=0.233),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU, crit_damage=0.14,
                  elem_mastery=40, crit_rate=0.101, atk_per=0.105),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU, hp_percent=0.128,
                  crit_rate=0.031, crit_damage=0.194, energy_recharge=0.052),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU, def_v=23,
                  crit_rate=0.128, crit_damage=0.07, atk_per=0.099),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU, crit_damage=0.256,
                  energy_recharge=0.097, def_per=0.058, atk_per=0.041),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_YU,
                  crit_rate=0.066, crit_damage=0.21, hp=299, atk_per=0.099),

        ShengYiWu(ShengYiWu.HUI_SHENG, ShengYiWu.PART_YU,
                  energy_recharge=0.097, elem_mastery=40, hp=299, crit_damage=0.218)

    ],
    ShengYiWu.PART_SHA: [
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_SHA, atk_per=ShengYiWu.BONUS_MAX,
                  def_per=0.051, crit_damage=0.194, crit_rate=0.093, hp=269),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  energy_recharge=0.045, crit_damage=0.078, crit_rate=0.113, def_v=60),

        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  atk=14, crit_rate=0.14, def_v=37, crit_damage=0.148),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_SHA, def_per=ShengYiWu.BONUS_MAX,
                  hp=508, crit_damage=0.132, crit_rate=0.058, atk=37),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_rate=0.027, def_v=23, crit_damage=0.264, hp=478),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  def_per=0.073, crit_rate=0.128, crit_damage=0.148, hp_percent=0.041),

        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  energy_recharge=0.052, crit_damage=0.202, elem_mastery=44, crit_rate=0.062),

        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_SHA, def_per=ShengYiWu.BONUS_MAX,
                  energy_recharge=0.11, crit_damage=0.202, atk_per=0.093, crit_rate=0.062),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_damage=0.319, def_v=19, crit_rate=0.031, energy_recharge=0.11),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_SHA, def_per=ShengYiWu.BONUS_MAX,
                  crit_damage=0.117, atk=14, crit_rate=0.113, energy_recharge=0.058),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_rate=0.07, hp=568, crit_damage=0.21, atk=16),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_damage=0.078, atk_per=0.087, crit_rate=0.132, def_v=16),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  atk=18, energy_recharge=0.091, crit_damage=0.218, crit_rate=0.074),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  atk_per=0.058, def_v=19, crit_damage=0.062, crit_rate=0.152),

        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  crit_rate=0.027, energy_recharge=0.11, def_per=0.204, crit_damage=0.21),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  crit_rate=0.128, atk=0.047, crit_damage=0.078, def_per=0.124),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  atk_per=0.14, def_v=35, crit_rate=0.062, atk=19),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  elem_mastery=23, crit_damage=0.218, def_v=44, crit_rate=0.07),

        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  crit_damage=0.117, crit_rate=0.128, hp=538, energy_recharge=0.045),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_SHA, atk_per=ShengYiWu.BONUS_MAX,
                  crit_rate=0.109, def_v=32, crit_damage=0.233, hp=209),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  crit_damage=0.124, hp_percent=0.198, energy_recharge=0.11, def_v=16),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_SHA, atk_per=ShengYiWu.BONUS_MAX,
                  hp=269, def_v=37, crit_damage=0.124, crit_rate=0.132),

        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_SHA, atk_per=ShengYiWu.BONUS_MAX,
                  elem_mastery=19, hp_percent=0.105, crit_rate=0.086, crit_damage=0.202),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  hp_percent=0.093, crit_damage=0.14, crit_rate=0.07, atk=35),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  hp=448, crit_rate=0.07, atk_per=0.082, def_v=44),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  crit_damage=0.194, elem_mastery=19, hp=508, def_per=0.117),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  hp_percent=0.117, crit_rate=0.027, def_per=0.19, crit_damage=0.14),

        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_SHA, def_per=ShengYiWu.BONUS_MAX,
                  elem_mastery=42, crit_damage=0.187, crit_rate=0.097, atk=18),
        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  crit_rate=0.066, hp_percent=0.082, crit_damage=0.123, energy_recharge=0.091),
        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  crit_damage=0.194, def_v=23, atk_per=0.047, crit_rate=0.101),
        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  atk=19, crit_damage=0.14, elem_mastery=33, crit_rate=0.105),
        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_SHA, def_per=ShengYiWu.BONUS_MAX,
                  elem_mastery=40, crit_damage=0.14, crit_rate=0.066, energy_recharge=0.117),
        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  atk=27, crit_damage=0.218, energy_recharge=0.104, atk_per=0.041),

        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_rate=0.066, atk=33, elem_mastery=40, crit_damage=0.21),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  def_v=37, energy_recharge=0.24, atk=19, crit_rate=0.07),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  energy_recharge=0.052, crit_damage=0.202, crit_rate=0.101, def_v=19),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  crit_rate=0.101, hp=508, atk_per=0.099, def_v=23),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  atk_per=0.099, crit_rate=0.078, elem_mastery=40, energy_recharge=0.117),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  elem_mastery=44, atk=16, energy_recharge=0.058, crit_damage=0.272),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  hp_percent=0.105, elem_mastery=40, def_v=35, atk=35),

        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  hp=448, crit_damage=ShengYiWu.CRIT_RATE_MAIN, def_per=0.073, elem_mastery=40),

        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  hp=508, def_v=37, crit_damage=0.078, def_per=0.182),
        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  def_v=65, elem_mastery=37, hp_percent=0.047, atk=37),

        ShengYiWu(ShengYiWu.YUE_TUAN, ShengYiWu.PART_SHA, atk_per=ShengYiWu.BONUS_MAX,
                  def_per=0.124, crit_rate=0.101, crit_damage=0.132, atk=19),

        ShengYiWu(ShengYiWu.FENG_TAO, ShengYiWu.PART_SHA, energy_recharge=ShengYiWu.ENERGY_RECHARGE_MAX,
                  crit_damage=0.078, crit_rate=0.086, atk_per=0.204, def_v=16),
        ShengYiWu(ShengYiWu.FENG_TAO, ShengYiWu.PART_SHA, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  atk=33, crit_rate=0.093, crit_damage=0.14, energy_recharge=0.13),

        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_rate=0.097, energy_recharge=0.11, elem_mastery=19, crit_damage=0.21),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_SHA, atk_per=ShengYiWu.BONUS_MAX,
                  atk=14, def_v=37, crit_damage=0.14, crit_rate=0.124),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  energy_recharge=0.091, crit_rate=0.163, crit_damage=0.078, hp=239),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_SHA, atk_per=ShengYiWu.BONUS_MAX,
                  crit_rate=0.097, hp=209, crit_damage=0.202, def_v=42),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_rate=0.109, atk_per=0.053, crit_damage=0.21, def_v=21),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_SHA, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_rate=0.031, def_v=23, crit_damage=0.295, energy_recharge=0.104),
    ],
    ShengYiWu.PART_BEI: [
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  atk=35, def_v=23, elem_mastery=70, crit_rate=0.109),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.LEI,
                  atk_per=0.082, atk=35, energy_recharge=0.045, crit_damage=0.225),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.SHUI,
                  crit_damage=0.132, energy_recharge=0.11, def_v=62, def_per=0.073),

        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.YAN,
                  energy_recharge=0.065, hp=1046, crit_damage=0.21, atk=19),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.BING,
                  crit_rate=0.105, elem_mastery=35, hp_percent=0.093, atk_per=0.082),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_rate=0.031, crit_damage=0.218, elem_mastery=37, def_v=37),
        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  energy_recharge=0.045, crit_rate=0.105, atk=18, hp=657),

        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_rate=0.093, def_per=0.131, def_v=23, crit_damage=0.21),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.BING,
                  atk=35, atk_per=0.111, elem_mastery=19, crit_rate=0.128),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.CAO,
                  def_v=16, crit_damage=0.07, crit_rate=0.167, hp=239),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  atk=27, def_per=0.066, crit_damage=0.132, crit_rate=0.097),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.HUO,
                  crit_rate=0.035, def_v=44, atk_per=0.053, crit_damage=0.28),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.SHUI,
                  hp_percent=0.163, crit_damage=0.14, energy_recharge=0.052, atk=27),

        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.YAN,
                  def_v=37, hp=508, crit_rate=0.101, crit_damage=0.14),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  atk=33, energy_recharge=0.097, crit_rate=0.144, elem_mastery=21),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.FENG,
                  crit_rate=0.086, energy_recharge=0.065, crit_damage=0.218, def_per=0.131),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.FENG,
                  energy_recharge=0.123, atk_per=0.053, crit_damage=0.07, crit_rate=0.14),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.BING,
                  atk_per=0.158, crit_damage=0.132, energy_recharge=0.065, elem_mastery=40),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.SHUI,
                  atk=16, crit_rate=0.074, hp_percent=0.204, hp=209),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.FENG,
                  crit_damage=0.194, elem_mastery=44, energy_recharge=0.052, crit_rate=0.062),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.LEI,
                  hp_percent=0.111, crit_rate=0.066, crit_damage=0.225, def_v=21),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.SHUI,
                  crit_rate=0.109, def_v=32, hp=478, hp_percent=0.058),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.CAO,
                  crit_rate=0.101, elem_mastery=19, crit_damage=0.179, hp=209),

        ShengYiWu(ShengYiWu.SHA_SHANG, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.LEI,
                  crit_rate=0.07, atk_per=0.053, atk=54, crit_damage=0.132),

        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.HUO,
                  crit_damage=0.202, elem_mastery=40, hp=239, crit_rate=0.058),

        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.BING,
                  hp=239, crit_rate=0.066, atk_per=0.21, atk=37),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.CAO,
                  atk=19, energy_recharge=0.123, crit_rate=0.113, hp_percent=0.087),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.FENG,
                  crit_damage=0.148, atk=14, crit_rate=0.121, def_v=19),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.HUO,
                  crit_rate=0.062, crit_damage=0.28, atk=14, def_v=16),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.CAO,
                  hp_percent=0.163, energy_recharge=0.045, elem_mastery=40, crit_rate=0.074),

        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.LEI,
                  crit_damage=0.179, elem_mastery=91, atk=19, def_per=0.073),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.HUO,
                  hp_percent=0.058, elem_mastery=23, atk_per=0.204, crit_rate=0.074),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.YAN,
                  crit_damage=0.14, def_per=0.233, crit_rate=0.027, atk_per=0.047),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_BEI, atk_per=ShengYiWu.BONUS_MAX,
                  crit_damage=0.218, crit_rate=0.066, def_v=39, energy_recharge=0.058),


        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_damage=0.062, def_v=19, crit_rate=0.167, def_per=0.058),
        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.BING,
                  atk_per=0.105, elem_mastery=33,  atk=33, crit_damage=0.187),

        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_BEI, atk_per=ShengYiWu.BONUS_MAX,
                  energy_recharge=0.214, atk=33, crit_damage=0.07, crit_rate=0.035),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.FENG,
                  hp_percent=0.093, def_v=16, energy_recharge=0.162, hp=538),
        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.SHUI,
                  hp=717, hp_percent=0.146, def_per=0.073, crit_damage=0.07),

        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.BING,
                  def_per=0.058, crit_rate=0.07, crit_damage=0.218, atk=33),

        ShengYiWu(ShengYiWu.QI_SHI_DAO, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.CAO,
                  elem_mastery=40, energy_recharge=0.058, crit_damage=0.241, hp_percent=0.047),

        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_BEI, atk_per=ShengYiWu.BONUS_MAX,
                  crit_damage=0.194, def_per=0.124, def_v=42, energy_recharge=0.117),
        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  energy_recharge=0.117, hp=568, def_v=58, crit_damage=0.07),
        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_BEI,
                  hp_percent=ShengYiWu.BONUS_MAX, hp=269, def_v=72, elem_mastery=44, atk=14),

        ShengYiWu(ShengYiWu.YUE_TUAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.BING,
                  crit_damage=0.179, crit_rate=0.105, atk=14, elem_mastery=40),
        ShengYiWu(ShengYiWu.YUE_TUAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.SHUI,
                  atk=29, crit_damage=0.241, hp=239, hp_percent=0.099),
        ShengYiWu(ShengYiWu.YUE_TUAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.HUO,
                  hp_percent=0.041, crit_damage=0.14, crit_rate=0.105, hp=568),
        ShengYiWu(ShengYiWu.YUE_TUAN, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.SHUI,
                  hp=538, crit_damage=0.078, atk_per=0.152, crit_rate=0.074),

        ShengYiWu(ShengYiWu.JUE_DOU_SHI, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.HUO,
                  atk_per=0.163, energy_recharge=0.065, atk=29, crit_damage=0.202),

        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.YAN,
                  atk=33, def_per=0.117, energy_recharge=0.13, crit_rate=0.101),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  atk=27, crit_damage=0.225, crit_rate=0.058, def_v=46),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_BEI, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_rate=0.07, energy_recharge=0.091, atk_per=0.105, crit_damage=0.148),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.BING,
                  crit_damage=0.21, hp_percent=0.058, energy_recharge=0.155, atk_per=0.047),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.SHUI,
                  atk=14, hp_percent=0.14, crit_damage=0.202, hp=269),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.HUO,
                  crit_rate=0.031, energy_recharge=0.097, elem_mastery=21, crit_damage=0.256),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.LEI,
                  energy_recharge=0.123, crit_damage=0.148, atk_per=0.105, crit_rate=0.066),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_BEI, elem_mastery=ShengYiWu.ELEM_MASTERY_MAIN,
                  hp_percent=0.053, crit_damage=0.202, energy_recharge=0.052, crit_rate=0.097),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_BEI, elem_bonus=ShengYiWu.BONUS_MAX, elem_type=Ys_Elem_Type.BING,
                  atk_per=0.192, hp=299, energy_recharge=0.11, atk=16),
    ],
    ShengYiWu.PART_TOU: [
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_TOU, hp_percent=ShengYiWu.BONUS_MAX,
                  crit_damage=0.202, crit_rate=0.074, def_per=0.066, def_v=63),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_TOU,
                  crit_rate=ShengYiWu.CRIT_RATE_MAIN, def_v=37, hp=239, atk=33, hp_percent=0.157),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  def_v=39, elem_mastery=44, hp=896, crit_damage=0.078),
        ShengYiWu(ShengYiWu.JU_TUAN, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  hp=478, hp_percent=0.111, atk_per=0.087, crit_rate=0.066),

        ShengYiWu(ShengYiWu.LIE_REN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  def_v=42, crit_damage=0.202, def_per=0.102, elem_mastery=16),

        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  crit_damage=0.14, def_v=56, hp=269, energy_recharge=0.168),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  atk=18, def_v=56, atk_per=0.105, crit_rate=0.093),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  crit_damage=0.132, atk=53, hp_percent=0.105, atk_per=0.041),
        ShengYiWu(ShengYiWu.HUA_HAI, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  def_per=0.058, hp=687, hp_percent=0.111, crit_rate=0.07),

        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  def_v=21, crit_damage=0.124, hp_percent=0.204, hp=538),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  atk_per=0.093, atk=19, crit_damage=0.187, elem_mastery=68),
        ShengYiWu(ShengYiWu.SHUI_XIAN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  energy_recharge=0.155, atk=14, hp=508, crit_damage=0.132),

        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  hp_percent=0.169, crit_rate=0.078, elem_mastery=63, atk_per=0.053),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  hp=448, atk=37, hp_percent=0.099, crit_rate=0.097),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  def_v=21, crit_damage=0.14, atk=33, elem_mastery=58),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  def_per=0.058, energy_recharge=0.227, atk_per=0.058, crit_damage=0.155),
        ShengYiWu(ShengYiWu.SHI_JIN, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  atk=33, crit_rate=0.101, def_v=16, atk_per=0.087),

        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  elem_mastery=47, def_v=32, atk_per=0.152, crit_rate=0.066),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_TOU, hp_percent=ShengYiWu.BONUS_MAX,
                  def_v=21, crit_damage=0.202, crit_rate=0.097, hp=239),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_TOU, hp_percent=ShengYiWu.BONUS_MAX,
                  energy_recharge=0.142, atk=19, crit_damage=0.132, crit_rate=0.066),
        ShengYiWu(ShengYiWu.SHEN_LIN, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  atk=19, def_v=35, crit_rate=0.132, energy_recharge=0.052),

        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  atk_per=0.053, hp=239,  crit_damage=0.358, def_v=37),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  atk_per=0.047, crit_damage=0.256, energy_recharge=0.104, hp=209),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  atk=31, crit_damage=0.179, def_per=0.058, energy_recharge=0.104),
        ShengYiWu(ShengYiWu.JUE_YUAN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  crit_damage=0.218, hp_percent=0.087, elem_mastery=16, atk_per=0.099),

        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  hp_percent=0.041, atk=18, elem_mastery=84, crit_rate=0.062),
        ShengYiWu(ShengYiWu.ZHUI_YI, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  elem_mastery=40, atk_per=0.053, energy_recharge=0.162, crit_damage=0.14),

        ShengYiWu(ShengYiWu.QIAN_YAN, ShengYiWu.PART_TOU, hp_percent=ShengYiWu.BONUS_MAX,
                  hp=209, crit_rate=0.074, atk=18, crit_damage=0.241),

        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  energy_recharge=0.058, def_v=37, crit_damage=0.155, hp_percent=0.134),
        ShengYiWu(ShengYiWu.CHEN_LUN, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  def_v=44, crit_damage=0.225, energy_recharge=0.097, elem_mastery=23),

        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  hp=299, atk=16, def_per=0.321, crit_damage=0.14),
        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  def_per=0.109, crit_rate=0.148, atk_per=0.058, energy_recharge=0.058),
        ShengYiWu(ShengYiWu.ZONG_SHI, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  def_v=60, crit_damage=0.187, hp=269, elem_mastery=47),

        ShengYiWu(ShengYiWu.RU_LEI, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  hp=777, atk=27, crit_damage=0.132, elem_mastery=23),

        ShengYiWu(ShengYiWu.FENG_TAO, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  crit_damage=0.272, def_v=23, hp=538, hp_percent=0.041),

        ShengYiWu(ShengYiWu.JUE_DOU_SHI, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  atk=19, crit_damage=0.194, hp=568, atk_per=0.093),
        ShengYiWu(ShengYiWu.JUE_DOU_SHI, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  hp_percent=0.053, crit_damage=0.303, hp=209, atk=39),

        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  hp_percent=0.041, crit_rate=0.124, def_v=58, atk=14),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN,
                  atk=14, energy_recharge=0.188, elem_mastery=56, crit_rate=0.078),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  def_per=0.073, energy_recharge=0.045, hp=478, crit_damage=0.264),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN, 
                  atk_per=0.058, def_per=0.292, crit_rate=0.031, def_v=46),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_TOU, crit_damage=ShengYiWu.CRIT_DAMAGE_MAIN, 
                  crit_rate=0.078, def_v=32, energy_recharge=0.104, atk_per=0.087),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_TOU, atk_per=ShengYiWu.BONUS_MAX,
                  crit_rate=0.101, crit_damage=0.124, elem_mastery=40, hp_percent=0.047),
        ShengYiWu(ShengYiWu.BING_TAO, ShengYiWu.PART_TOU, crit_rate=ShengYiWu.CRIT_RATE_MAIN,
                  atk_per=0.152, elem_mastery=44, crit_damage=0.148, def_v=23),
    ]
}